BOT_TOKEN = "TOKEN_BOT_KAMU"

QRIS_API_KEY = "API_KEY_QRIS_PW"
QRIS_API_SECRET = "API_SECRET_QRIS_PW"

QRIS_CREATE_URL = "https://api.qris.pw/api/v1/qris/create"

GROUP_ID = -1001234567890  # ID grup private
